title: Yuanpeng Chen's Homepage
page-top-title: Yuanpeng Chen
top-section-bg-text: Geographic Data Science
home-subtitle: Yuanpeng Chen&ensp;|&ensp;GIS Student
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
