title: Yuanpeng Chen's Homepage
page-top-title: Yuanpeng Chen
top-section-bg-text: Geographic Data Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
